rvm:
  - jruby
  - jruby-head
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
env:
  - JRUBY_OPTS="--1.8 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
  - JRUBY_OPTS="--1.9 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
