rvm:
  - jruby
  - jruby-head
branches:
  only:
    - master
env:
  - JRUBY_OPTS="--1.8 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
  - JRUBY_OPTS="--1.9 --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
matrix:
  include:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: 1.9.3
